#include <paging/allocator/free_pages.h>

free_page_info_t free_pages_info_1[PAGING_REGIONS_COUNT_1];
free_page_info_t free_pages_info_2[PAGING_REGIONS_COUNT_2];
free_page_info_t free_pages_info_4[PAGING_REGIONS_COUNT_4];
free_page_info_t free_pages_info_8[PAGING_REGIONS_COUNT_8];
free_page_info_t free_pages_info_16[PAGING_REGIONS_COUNT_16];
free_page_info_t free_pages_info_32[PAGING_REGIONS_COUNT_32];
free_page_info_t free_pages_info_64[PAGING_REGIONS_COUNT_64];
free_page_info_t free_pages_info_128[PAGING_REGIONS_COUNT_128];

uint64_t free_pages_1[PAGING_REGIONS_COUNT_1];
uint64_t free_pages_2[PAGING_REGIONS_COUNT_2];
uint64_t free_pages_4[PAGING_REGIONS_COUNT_4];
uint64_t free_pages_8[PAGING_REGIONS_COUNT_8];
uint64_t free_pages_16[PAGING_REGIONS_COUNT_16];
uint64_t free_pages_32[PAGING_REGIONS_COUNT_32];
uint64_t free_pages_64[PAGING_REGIONS_COUNT_64];
uint64_t free_pages_128[PAGING_REGIONS_COUNT_128];