#pragma once

typedef enum {
    SYSCALL_OPEN      = 0,
    SYSCALL_CLOSE     = 1,
    SYSCALL_WRITE     = 2,
    SYSCALL_READ      = 3,
    SYSCALL_SEEK      = 4,
    SYSCALL_EXIT      = 5,
    SYSCALL_READDIR   = 6,
    SYSCALL_CHDIR     = 7,
    SYSCALL_FORK      = 8,
    SYSCALL_EXEC      = 9,
    SYSCALL_MAP       = 10,
    SYSCALL_WAIT      = 11,
    SYSCALL_PIPE      = 12,
    SYSCALL_DUP       = 13,
    SYSCALL_MOUNT     = 14,
    SYSCALL_UNMOUNT   = 15,
    SYSCALL_MKDIR     = 16,
    SYSCALL_REMOVE    = 17,
    SYSCALL_OPENAT    = 18,
    SYSCALL_SOCKET    = 19,
    SYSCALL_CONNECT   = 20,
    SYSCALL_BIND      = 21,
    SYSCALL_LISTEN    = 22,
    SYSCALL_ACCEPT    = 23,
    SYSCALL_SIGNAL    = 24,
    SYSCALL_SIGNALRET = 25,
    SYSCALL_ALARM     = 26,
    SYSCALL_KILL      = 27,
    SYSCALL_THREAD    = 28,

    _SYSCALL_COUNT,
} syscall_number_t;

